title = "Secure Reporting System (Client)"

[client]
level = 3                   # Access priority
password = "password"       # Password for AES-256 encryption
send_time = "00:00"         # Time of day to send reports
targets = [                 # Locations of the log files to be reported
    "file1.txt",
    "file2.txt",
    ]

[server]
address = "127.0.0.1"       # IP address of the SRS server
port = 8080                 # Which port the server is listening on
public_key = "server_public-key.pem"   # Name/location of the server's public key file
