title = "Secure Reporting System (Client)"

[client]
level = 3                   # Access priority
targets = [                 # Locations of the log files to be reported
    "path/to/file1",
    "path/to/file2",
    ]

[server]
address = "127.0.0.1"       # IP address of the SRS server
port = 8080                 # Which port the server is listening on
public_key = "server.pub"   # Name/location of the server's public key file
