title = "Secure Reporting System (Server)"

[server]
port = 8080                             # Which port the server is listening on
private_key = "server_private-key.pem"  # Name/location of the server's private key file

[client]                                # Password for AES-256 encryption
whitelist = [                           # List of client IPs that are allowed to connect
    "127.0.0.1",
    "192.168.1.1",
    "192.168.1.2",
    ]